export const authConstant ={
    LOGIN_REQUEST: 'LOGIN REQUEST',
    LOGIN_SUCCESS: 'LOGIN SUCCESS',
    LOGIN_FAILURE: 'LOGIN FAILURE',
    LOGOUT_REQUEST: 'LOGOUT REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT FAILURE'
}

export const userConstants={
    USER_REGISTER_REQUEST: 'USER REGISTER REQUEST',
    USER_REGISTER_SUCCESS: 'USER REGISTER SUCCESS',
    USER_REGISTER_FAILURE: 'USER REGISTER FAILURE'
}

export const categoryConstants={
    GET_ALL_CATEGORIES_REQUEST: 'GET ALL CATEGORIES REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET ALL CATEGORIES SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET ALL CATEGORIES FAILURE',
    ADD_CATEGORIES_REQUEST: 'ADD CATEGORIES REQUEST',
    ADD_CATEGORIES_SUCCESS: 'ADD CATEGORIES SUCCESS',
    ADD_CATEGORIES_FAILURE: 'ADD CATEGORIES FAILURE',
}

export const initialDataContants={
    GET_ALL_INITIALDATA_REQUEST: 'GET ALL INITIAL DATA REQUEST',
    GET_ALL_INITIALDATA_SUCCESS: 'GET ALL INITIAL DATA SUCCESS',
    GET_ALL_INITIALDATA_FAILURE: 'GET ALL INITIAL DATA FAILURE',

}

export const productsContants={
     GET_ALL_PRODUCTS_REQUEST:'GET ALL PRODUCTS REQUEST',
     GET_ALL_PRODUCTS_SUCCESS:'GET ALL PRODUCTS SUCCESS',
     GET_ALL_PRODUCTS_FAILURE:'GET ALL PRODUCTS FAILURE',
}