export const authConstant ={
    LOGIN_REQUEST: 'LOGIN REQUEST',
    LOGIN_SUCCESS: 'LOGIN SUCCESS',
    LOGIN_FAILURE: 'LOGIN FAILURE',
    LOGOUT_REQUEST: 'LOGOUT REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT FAILURE'
}

export const userConstants={
    USER_REGISTER_REQUEST: 'USER REGISTER REQUEST',
    USER_REGISTER_SUCCESS: 'USER REGISTER SUCCESS',
    USER_REGISTER_FAILURE: 'USER REGISTER FAILURE'
}

export const categoryConstants={
    GET_ALL_CATEGORIES_REQUEST: 'GET ALL CATEGORIES REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET ALL CATEGORIES SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET ALL CATEGORIES FAILURE',
    ADD_CATEGORIES_REQUEST: 'ADD CATEGORIES REQUEST',
    ADD_CATEGORIES_SUCCESS: 'ADD CATEGORIES SUCCESS',
    ADD_CATEGORIES_FAILURE: 'ADD CATEGORIES FAILURE',
    UPDATE_CATEGORIES_REQUEST: 'UPDATE CATEGORIES REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE CATEGORIES SUCCESS',
    UPDATE_CATEGORIES_FAILURE: 'UPDATE CATEGORIES FAILURE',
    DELETE_CATEGORIES_REQUEST: 'DELETE CATEGORIES REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE CATEGORIES SUCCESS',
    DELETE_CATEGORIES_FAILURE: 'DELETE CATEGORIES FAILURE'
}

export const initialDataContants={
    GET_ALL_INITIALDATA_REQUEST: 'GET ALL INITIAL DATA REQUEST',
    GET_ALL_INITIALDATA_SUCCESS: 'GET ALL INITIAL DATA SUCCESS',
    GET_ALL_INITIALDATA_FAILURE: 'GET ALL INITIAL DATA FAILURE',

}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
  
    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",
  
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  };

export const pageConstants = {
    CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE'
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };