export const authConstant ={
    LOGIN_REQUEST: 'LOGIN REQUEST',
    LOGIN_SUCCESS: 'LOGIN SUCCESS',
    LOGIN_FAILURE: 'LOGIN FAILURE',
    LOGOUT_REQUEST: 'LOGOUT REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT FAILURE'
}

export const userConstants={
    USER_REGISTER_REQUEST: 'USER REGISTER REQUEST',
    USER_REGISTER_SUCCESS: 'USER REGISTER SUCCESS',
    USER_REGISTER_FAILURE: 'USER REGISTER FAILURE'
}

export const categoryConstants={
    GET_ALL_CATEGORIES_REQUEST: 'GET ALL CATEGORIES REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET ALL CATEGORIES SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET ALL CATEGORIES FAILURE'
}